### ISSUE TITLE
CH Core Coverage: subsriberId binding to AHVN13? (Walter Wellauer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#104]
ch.fhir.ig.ch-core#1.2.0 /StructureDefinition-ch-core-coverage-definitions.html

subscriberId binding to AHNN13 might be considered

Walter Wellauer, Cistec AG

**Comment by oliveregger** [comment]
Gemäss Jürg darf AHVN13 nicht in als subscriberID gebraucht werden das es das Gesetz nicht zulässt. 
Gemäss Marcel ist im Rahmen von IV die Angabe von AHVN13 zwingend.

**Comment by oliveregger** [comment]
Es gibt verschiedene Insurer in der Schweiz mit verschiedenen Angaben für die subscriberId.
subscriberdId: The insurer requires this identifier on correspondance and claims (digital and otherwise).
zum Beispiel:
- Zusatzversicherung: eigenen Nummer oder KDV
- UVG: Fallnummer

Es kann nicht die AHVN13 alleine verwendet werden.
Kann geschlossen werden: 12 - 0 - 0
