### ISSUE TITLE
CH Core Practitioner Profile (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#124]
ch.fhir.ig.ch-core#2.0.0 /StructureDefinition-ch-core-practitioner.html

HumanName is 0..* but there is a constraint which requires HumanName to be 1..*
At least one HumanName with given and family name must be provided.

either it should be 1..* or the rule should be changed to: If HumanNames are provided, at least one HumanName must have a given and family name.

Oliver Egger, ahdis

**Comment by regelkraut** [comment]
Dear sender, 

due to a ransomware attack and necessary security measures, CGM is temporarily not reachable via the usual eMail addresses and landline numbers. 
Please feel free to use SMS and mobile telephony of your individual contact persons, as far as they are known to you or inform yourself about further contact possibilities via the respective company or product page. 

Thank you for your understanding and best regards,
Your CGM Team

----------------------------

Sehr geehrte Absenderin, 
sehr geehrter Absender,  

aufgrund einer Ransomware-Attacke und notwendiger Sicherheitsmaßnahmen, ist CGM vorübergehend nicht über die gewohnten eMail-Adressen und Festnetznummern erreichbar. 
Bitte nutzen Sie gerne SMS und Mobilfunk-Telefonie Ihrer individuellen Ansprechpartner, soweit diese ihnen bekannt sind oder informieren Sie sich über die jeweilige Firmen- bzw. Produktseite über weitere Kontaktmöglichkeiten. 

Vielen Dank für Ihr Verständnis und freundliche Grüße, 
Ihr CGM-Team

**Comment by oliveregger** [comment]
angenommen: 11 - 0 -0
